---
output:
  pdf_document: default
---
# Problem Description {#problem-description}

To understand how the computational framework is established, first the MDRP is described.
In addition to the definition that is reviewed from the literature, new contributions are made to capture missing aspects from a real-life operation and the corresponding assumptions are given.

## The Meal Delivery Routing Problem (MDRP) {#the_meal_delivery_routing_problem}
The MDRP is considered as defined by @mdrp and restated here for completeness.
It is paraphrased in a different manner to adapt it to this research, while keeping all of its elements and logic.

Let $U$ be the set of users, who want meals delivered and place orders, with each user $u \in U$ having a drop-off location $\ell_u$.
Let $R$ be the set of restaurants, where meals must be picked up, and each restaurant $r \in R$ has a pick-up location $\ell_r$.
Then, let $O$ be the set of orders placed by the users.
Each order $o \in O$ has an associated restaurant $r_o \in R$ and user $u_o \in U$, a placement time $a_o$, a ready time $e_o$, a pick-up service time $s^r$ (depending on the restaurant) and a drop-off service time $s^u$ (linked to the user).
Let $C$ be the set of couriers, who are used to deliver the orders in $O$.
Let $c_o \in C$ be the courier assigned to order $o \in O$, noting that a courier may eventually *not* be assigned.
Each courier $c \in C$ has an on-time $e_c$, an on-location $\ell_c$, and an off-time $l_c$, with $l_c > e_c$.
A courier's compensation at the end of the shift is defined as $max \{p_1m_c, p_2(l_c - e_c)\}$, where $p_1$ is a fixed compensation per order delivered, $m_c$ is the number of orders delivered during the shift and $p_2$ is a fixed compensation rate per hour.
Orders from the same restaurant may be aggregated into bundles, or routes, where each route has a single pick-up but multiple drop-off locations. 
Let $S$ be the set of routes.
Any route $s \in S$ must fulfill $|\{r_o, \space \forall \space o \in S\}| = 1$.
All information about $R$ and $C$ is completely known.
The information about a user and its associated order is only revealed at placement time $a_o$.
In summation, the MDRP consists of:

>*"...determining feasible routes for couriers to complete the pick-up and delivery of orders, with the objective to optimize a single or multiple performance measures."*
>
> ---[@mdrp]

In the operating environment, the following two practices take place:

1. *Prepositioning*. 
A courier can be notified of an instruction to pick up & drop off a route or to move to a new location, changing the courier's current position.
1. *Assignment Updates*. 
When a courier is picking up an order at a restaurant, new notifications to pick up additional orders may be received, as long as they belong to the same restaurant.

## Novel Characteristics {#novel_characteristics}
Contributing to the definition of the problem, the following novel features, which are not considered in the literature are added to accurately represent a real-life operation:

1. Couriers are able to freely move about the city when idling, actively making decisions of whether and where they want to move. 
At every time fraction $f_r$, this is $t \mod f_r = 0, \space \forall \space t \in T$, the courier evaluates if they want to relocate.
Let $\ell_{c, t}$ be the location of courier $c \in C$ at time $t \in T$, then $\ell_{c, t + 1} = \mathbb{P}_{me}(\ell_{c, t})$ is the location of courier $c \in C$ at time $t + 1$ governed by the *movement evaluation* policy $\mathbb{P}_{me}$, whose output may well be $\ell_{c, t + 1} = \ell_{c, t}$ or $\ell_{c, t + 1} \neq \ell_{c, t}$.
1. The dispatcher can notify pick-up & drop-off or prepositioning requests.
This feature is considered in the MDRP but lacks formal definition.
Let $N_t$ be the set of notifications at time $t \in T$. 
Each notification $n \in N_t$ can be of type prepositioning ($n_p$) or pick-up & drop-off ($n_{pd}$), thus $n \in \{n_p \cap n_{pd} = \varnothing\}$.
Each notification has an associated location $\ell_n$.
Let $c_n$ be the courier and $s_n$ the route associated to notification $n \in N$.
For prepositioning notifications, the location is the projected destination and for pick-up & drop-off notifications, the location is the first stop of the route, this is, the pick-up location $\ell_r$.
1. Couriers may accept or reject notifications generated by the system.
Let $h_{\ell_1, \ell_2}$ be the haversine distance between location $\ell_1$ and $\ell_2$.
Given that a courier may accept or reject a notification, each courier $c \in C$ has an acceptance rate $p_c$.
A courier accepts a notification based on probability $P_c = f(h_{\ell_{c, t}, \ell_{n}}, p_c)$, with $P_c > 0$.
This acceptance function has a positive domain over $h_{\ell_{c, t}, \ell_{n}}$ and $p_c$.
The acceptance function fulfills that $P_c \propto 1 / h_{\ell_{c, t}, \ell_{n}}$ and $P_c \propto h_c$.
One can see that a courier tends to reject a notification proportionately to having a lower acceptance rate or it being far away.
1. Each courier has a vehicle that alters the movement mechanics around the city.
Let $V$ be the set of vehicles and courier $c \in C$ has a vehicle $v_c \in V$.
1. Each order has a preparation time in which the meal *begins* cooking.
The preparation time is denoted as $d_o$ for order $o \in O$, and it fulfills $a_o \leq d_o$. 
The difference with the placement time $a_o$ is that the system keeps the order from the restaurant $r_o$ until $d_o$.
This opens up the MDRP to the possibility of having scheduled orders (such as groceries), where $a_o \ll d_o$. 
In the context of the original MDRP, $a_o = d_o$.
1. A user $u \in U$ has a cancellation time $t^u$. 
After $d_o + t^u$, if the order $o \in O$ has not been assigned to a courier, the user $u_o$ may decide to cancel it based on a user cancellation policy $\mathbb{P}_{uc}$ whose output is $\{0, 1\}$.
1. The system (or dispatcher as it is referred to in further sections) has a cancellation time $t^d$.
The dispatcher is the agent in charge of controlling the operation and thus is responsible for maintaining appropriate service levels.
After $d_o + t^d$, where $t^d > t^u$ and the order has no courier assigned, the dispatcher may decide to cancel the order based on the dispatcher's *cancellation* policy $\mathbb{P}_{dc}$ whose output is $\{0, 1\}$.
1. Every order $o \in O$ has an individual expected drop-off time $f_o'$, which is a different approach to having a generalized target drop-off time $\tau$ that would be the same for all orders.
The actual drop-off time of the order is $f_o$.
One goal of the solution of the MDRP must be to minimize the expected drop-off lateness for all orders, this is $|f_o' - f_o| \approx 0$.
1. The dispatcher evaluates sending pick-up & drop-off notifications at every time fraction $f$, this is $t \mod f = 0 , \space \forall \space t \in T$.
For a rolling horizon approach [@mdrp], $f > 0$ and the time fraction can be minutes.
For a clairvoyant approach [@provably], where all decisions are made at a single moment, $f = |T|$.
In addition, for an events-based solution [@event_driven_optimization], $f \approx 0$ and information is optimized as soon as it arrives.
This definition of $f$ allows flexibility in defining solutions for the MDRP.
1. The dispatcher evaluates sending prepositioning notifications at every time fraction $f_p$, $t \mod f_p = 0, \space \forall \space t \in T$,  and similar configurations to the previously described $f$ can be achieved.

## Structural Assumptions {#structural_assumptions}
The following assumptions are considered in the definition of this modified version of the MDRP:

- Any route $s \in S$ has a limited number of orders $S_{max}$.
- The travel time $b_{\ell_1, \ell_2}$ between any pair of locations $\ell_1$ and $\ell_2$ is invariant over time.
- A courier follows a city's real street layout while moving and respects traffic signals, independent of their vehicle.
- Couriers cannot be notified of new instructions after their off-time $l_c$ has passed but can finish any ongoing assignments.
- Couriers execute autonomous decisions, as described in characteristics 1 and 3 of the [**novel characteristics**](#novel_characteristics) section.
- Couriers can only be notified if they are idling or picking up an order (or group of orders).
If a courier is moving, due to safety concerns, the real-life practice of not notifying them is applied, as well as when a courier is dropping off an order, so they can focus on the task at hand.
- A user can only order once throughout the day, this is, any user has a single order associated to them.
In other problems, such as the Virtual Food Court Delivery Problem [@dynamic_courier_routing], users can have several orders simultaneously.
- A courier may only receive one notification at the same time.
- An order may only be assigned to a single courier.
- Prepositioning notifications and assignment updates are encouraged and performed by the dispatcher.
- Once an order is canceled, either by the user or the dispatcher, it cannot return to the system and negatively impacts service metrics.
- A courier's vehicle is invariant over time.
- The system's information regarding $U$, $R$, $C$ and $O$ is deterministic.

## Performance Metrics {#performance-metrics}
To measure a solution for the MDRP the following performance metrics are considered as written by @mdrp:

1. Number of orders delivered.
1. Total courier compensation.
1. Cost per order: total courier compensation divided by number of orders delivered.
1. Fraction of couriers receiving guaranteed minimum compensation.
1. Click-to-door time: the difference between the drop-off time and the placement time of an order.
1. Click-to-door time overage: the difference between the drop-off time of an order and the placement time of an order plus the target click-to-door time.
1. Ready-to-door time: the difference between the drop-off time of an order and the ready time of an order.
1. Ready-to-pickup time: the difference between the pick-up time of an order and its ready time.
1. Courier utilization: the fraction of the courier duty time that is devoted to driving, pick-up service, and drop-off service (as opposed to time spent waiting).
1. Courier delivery earnings: courier earnings when considering only the number of orders served.
1. Courier compensation: the maximum of the guaranteed minimum compensation (based on the length of the duty period) and the delivery earnings.
1. Orders delivered per hour: for each courier, the number of orders delivered divided by the length of the shift.
1. Bundles picked up per hour: for each courier, the number of order bundles assigned divided by the length of the shift.
1. Orders per bundle: for each assignment, the number of orders to be picked up.

New performance metrics are added to capture important outcomes:

1. In-store-to-pickup time: the difference between the pick-up time and the time at which the courier arrives at the store.
This metric shows how in time are the couriers arriving to the restaurants.
1. Drop-off lateness: the absolute difference between the order's expected drop-off time and the actual drop-off time.
This metric captures quality of service for the user.
1. Number of canceled orders.
1. Fulfillment: delivered orders divided by the total orders (delivered and canceled).
A fulfillment of 100% is the target for any company.
1. Click-to-taken-time: the difference between the time an order is accepted by a courier and the placement time.
This metric captures how the global acceptance probability of the system behaves.
